Permit doing keybindings without modifiers
sminez/penrose pull request #161
Opened 2021-03-07 13:20 UTC by TethysSvensson

I would like to be able to add keybindings without modifiers, e.g. for volume or brightness keys on my keyboard. As far as I can tell, the runtime code has no issues with this at all, however the compile-time validator is not happy when I try.

This PR makes the compile-time validator a bit less strict, but will not change anything besides that.

2021-03-07 13:48 UTC, sminez requested changes
This _looks_ fine (and I'd assume this doesn't cause issues) but I'd prefer to get some tests in place around the proc-macro itself before merging this. I added the `stubbed_companion_trait` macro after this one and I had more of an understanding of how to test proc-macros at that point. Some simple tests covering each of the cases should be enough:

- binding with a modifier (valid / invalid modifier, valid / invalid keyname)
- binding without a modifier (valid / invalid keyname)

I'll get the "with modifier" ones written now and pushed to develop, can you rebase your branch once those are in and make sure that they still pass and then add corresponding cases for your change?

2021-03-07 14:27 UTC, sminez commented
Ah hang on, the existing `crates` tests are not running in CI _or_ under `make check-all` :facepalm:

Fixing that now

2021-03-07 19:41 UTC, TethysSvensson commented
I have rebased on top of the current head. `make check-all` passes on my machine. I will add some tests now.

2021-03-07 19:56 UTC, TethysSvensson commented
I have added tests now :smile:

2021-03-08 09:27 UTC, sminez requested changes
The new test cases look good and the stderr output is what I was expecting, but can you please move the modifier-less cases out to their own files instead of adding them to the existing ones? I'd like it to be as clear as possible when test cases fail what the cause is and having two failure messages in a single `stderr` file might make things confusing in future 😅 

I'm also realising that if this change to allow bindings without modifiers is going in, there probably also needs to be an update to the [docs](https://github.com/sminez/penrose/blob/develop/src/core/macros.rs#L100) for the `gen_keybindings` macro to cover it (and possibly some uses of it in the example configs).

Once that's done, this should be good to merge 👍

2021-03-10 11:39 UTC, TethysSvensson commented
@sminez Done! :smile:

2021-03-10 12:27 UTC, sminez approved these changes
:shipit:

2021-03-10 12:27 UTC, merged