Allow string with spaces as dmenu prompt (again).
sminez/penrose pull request #258
Opened 2023-02-15 11:42 UTC by Netzwerk2

Fixes #257.

I also changed the the `flags` method to return an iterator, which removes one `collect` statement.

2023-02-15 13:35 UTC, sminez requested changes
Sorry about the regression with this. The actual fix itself is fine (building as Vec directly rather than building and splitting a string) but there's some odd usage of `extend_from_slice` which I'd prefer were just `push` and changing things to return an Iterator feels overly compicated for no real gain.

2023-02-15 13:35 UTC, sminez commented on src/extensions/util/dmenu.rs
> +            flags.extend_from_slice(&["-P".to_string()]);
I really don't understand why this is using `extend_from_slice` rather than `push`

2023-02-15 13:35 UTC, sminez commented on src/extensions/util/dmenu.rs
> +            flags.extend_from_slice(&["-i".to_string()]);
same here

2023-02-15 13:35 UTC, sminez commented on src/extensions/util/dmenu.rs
> +        flags.into_iter()
converting into an iterator doesn't get us anything here: the `Vec` that was returned before is accepted just fine in `raw_user_choice_from_dmenu` when building out the `Command`.

2023-02-15 15:50 UTC, Netzwerk2 commented
I forgot that I already created a Vec and was partly looking at the old code, thus I thought I could get rid of one allocation. As for the `extend_from_slice`, I really don't know why I used that instead of push. Both are fixed now.

2023-02-16 07:32 UTC, sminez approved these changes

2023-02-16 07:32 UTC, merged