feat: toggle_floating_state and is_floating (#306)
sminez/penrose pull request #307
Opened 2024-08-12 18:36 UTC by codybloemhard

In order to resolve issue #306

Adds:

- StackSet<Clone + PartialEq + Eq + Hash>::is_floating
- StackSet<Xid>::toggle_floating_state
- builtin::actions::floating::toggle_floating_focused

2024-08-12 22:18 UTC, sminez requested changes
Implementation looks good 👍 

If you can add some teats for the toggle method then this should be good to merge.There are equivalent tests for similar methods in the file already using the test_case macro to cover the different cases you highlight in the doc comment.

2024-08-12 22:18 UTC, sminez commented on src/pure/stack_set.rs
> +        })
Can this be bound to a variable and returned as `Ok(rect)` rather wrapping the whole if statement

2024-08-14 15:45 UTC, codybloemhard commented
I tried to split `toggle_floating_state` test case into two, one using `test_case` to check for the different errors it can return but I couldn't assert them because `Error` has no `PartialEq` and quickly adding it into the derive didn't work out.

2024-08-15 07:55 UTC, sminez approved these changes
A couple of minor style things but I'll fix those up post merge rather than nitpicking on this PR :slightly_smiling_face: 

Thank you for taking the time to contribute to Penrose!

2024-08-15 07:55 UTC, merged